### YamlMime:ManagedReference
items:
- uid: System.Web.Configuration.WebContext
  id: WebContext
  children:
  - System.Web.Configuration.WebContext.#ctor(System.Web.Configuration.WebApplicationLevel,System.String,System.String,System.String,System.String,System.String)
  - System.Web.Configuration.WebContext.ApplicationLevel
  - System.Web.Configuration.WebContext.ApplicationPath
  - System.Web.Configuration.WebContext.LocationSubPath
  - System.Web.Configuration.WebContext.Path
  - System.Web.Configuration.WebContext.Site
  - System.Web.Configuration.WebContext.ToString
  langs:
  - csharp
  name: WebContext
  nameWithType: WebContext
  fullName: System.Web.Configuration.WebContext
  type: Class
  summary: "Gestisce il contesto del percorso per l&quot;applicazione Web corrente. Questa classe non pu√≤ essere ereditata."
  remarks: ''
  example:
  - "The following example shows how to use the WebContext class.  \n  \n [!code-cs[System.Web.Configuration.WebContext#1](~/add/codesnippet/csharp/t-system.web.configurati_25_1.cs)]\n [!code-vb[System.Web.Configuration.WebContext#1](~/add/codesnippet/visualbasic/t-system.web.configurati_25_1.vb)]"
  syntax:
    content: public sealed class WebContext
  inheritance:
  - System.Object
  implements: []
  inheritedMembers: []
  platform:
  - net462
- uid: System.Web.Configuration.WebContext.#ctor(System.Web.Configuration.WebApplicationLevel,System.String,System.String,System.String,System.String,System.String)
  id: '#ctor(System.Web.Configuration.WebApplicationLevel,System.String,System.String,System.String,System.String,System.String)'
  parent: System.Web.Configuration.WebContext
  langs:
  - csharp
  name: WebContext(WebApplicationLevel,String,String,String,String,String)
  nameWithType: WebContext.WebContext(WebApplicationLevel,String,String,String,String,String)
  fullName: System.Web.Configuration.WebContext.WebContext(WebApplicationLevel,String,String,String,String,String)
  type: Constructor
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  summary: "Inizializza una nuova istanza di <xref href=&quot;System.Web.Configuration.WebContext&quot;> </xref> classe."
  remarks: ''
  example:
  - "The following example shows how to use this constructor. This code example is part of a larger example provided for the <xref:System.Web.Configuration.WebContext> class.  \n  \n [!code-cs[System.Web.Configuration.WebContext#2](~/add/codesnippet/csharp/c8cb0c76-e300-49bb-8742-_1.cs)]\n [!code-vb[System.Web.Configuration.WebContext#2](~/add/codesnippet/visualbasic/c8cb0c76-e300-49bb-8742-_1.vb)]"
  syntax:
    content: public WebContext (System.Web.Configuration.WebApplicationLevel pathLevel, string site, string applicationPath, string path, string locationSubPath, string appConfigPath);
    parameters:
    - id: pathLevel
      type: System.Web.Configuration.WebApplicationLevel
      description: "A <xref href=&quot;System.Web.Configuration.WebApplicationLevel&quot;></xref> object."
    - id: site
      type: System.String
      description: "Il nome del sito Web."
    - id: applicationPath
      type: System.String
      description: "Il percorso virtuale del livello radice dell&quot;applicazione Web corrente."
    - id: path
      type: System.String
      description: "Il percorso virtuale del file Web. config che rappresenta l&quot;oggetto di configurazione corrente."
    - id: locationSubPath
      type: System.String
      description: "Il valore del percorso di <xref uid=&quot;langword_csharp_location&quot; name=&quot;location&quot; href=&quot;&quot;> </xref> elemento che si sta modificando."
    - id: appConfigPath
      type: System.String
      description: "Percorso di configurazione dell&quot;applicazione Web corrente."
  overload: System.Web.Configuration.WebContext.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.Web.Configuration.WebContext.ApplicationLevel
  id: ApplicationLevel
  parent: System.Web.Configuration.WebContext
  langs:
  - csharp
  name: ApplicationLevel
  nameWithType: WebContext.ApplicationLevel
  fullName: System.Web.Configuration.WebContext.ApplicationLevel
  type: Property
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  summary: "Ottiene un <xref href=&quot;System.Web.Configuration.WebApplicationLevel&quot;> </xref> oggetto che rappresenta il livello di percorso dell&quot;applicazione Web corrente."
  remarks: ''
  example:
  - "The following example shows how to use the ApplicationLevel property. This code example is part of a larger example provided for the <xref:System.Web.Configuration.WebContext> class.  \n  \n [!code-cs[System.Web.Configuration.WebContext#3](~/add/codesnippet/csharp/p-system.web.configurati_226_1.cs)]\n [!code-vb[System.Web.Configuration.WebContext#3](~/add/codesnippet/visualbasic/p-system.web.configurati_226_1.vb)]"
  syntax:
    content: public System.Web.Configuration.WebApplicationLevel ApplicationLevel { get; }
    return:
      type: System.Web.Configuration.WebApplicationLevel
      description: "A <xref href=&quot;System.Web.Configuration.WebApplicationLevel&quot;></xref> object."
  overload: System.Web.Configuration.WebContext.ApplicationLevel*
  exceptions: []
  platform:
  - net462
- uid: System.Web.Configuration.WebContext.ApplicationPath
  id: ApplicationPath
  parent: System.Web.Configuration.WebContext
  langs:
  - csharp
  name: ApplicationPath
  nameWithType: WebContext.ApplicationPath
  fullName: System.Web.Configuration.WebContext.ApplicationPath
  type: Property
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  summary: "Ottiene il percorso dell&quot;applicazione dell&quot;applicazione Web corrente."
  remarks: ''
  example:
  - "The following example shows how to use the ApplicationPath property. This code example is part of a larger example provided for the <xref:System.Web.Configuration.WebContext> class.  \n  \n [!code-cs[System.Web.Configuration.WebContext#4](~/add/codesnippet/csharp/p-system.web.configurati_313_1.cs)]\n [!code-vb[System.Web.Configuration.WebContext#4](~/add/codesnippet/visualbasic/p-system.web.configurati_313_1.vb)]"
  syntax:
    content: public string ApplicationPath { get; }
    return:
      type: System.String
      description: "Il percorso dell&quot;applicazione dell&quot;applicazione Web corrente."
  overload: System.Web.Configuration.WebContext.ApplicationPath*
  exceptions: []
  platform:
  - net462
- uid: System.Web.Configuration.WebContext.LocationSubPath
  id: LocationSubPath
  parent: System.Web.Configuration.WebContext
  langs:
  - csharp
  name: LocationSubPath
  nameWithType: WebContext.LocationSubPath
  fullName: System.Web.Configuration.WebContext.LocationSubPath
  type: Property
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  summary: "Ottiene il sottopercorso del percorso dell&quot;applicazione Web."
  syntax:
    content: public string LocationSubPath { get; }
    return:
      type: System.String
      description: "Il sottopercorso del percorso dell&quot;applicazione Web corrente."
  overload: System.Web.Configuration.WebContext.LocationSubPath*
  exceptions: []
  platform:
  - net462
- uid: System.Web.Configuration.WebContext.Path
  id: Path
  parent: System.Web.Configuration.WebContext
  langs:
  - csharp
  name: Path
  nameWithType: WebContext.Path
  fullName: System.Web.Configuration.WebContext.Path
  type: Property
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  summary: "Ottiene il percorso virtuale corrente dell&quot;applicazione Web."
  remarks: ''
  example:
  - "The following example shows how to use the Path property. This code example is part of a larger example provided for the <xref:System.Web.Configuration.WebContext> class.  \n  \n [!code-cs[System.Web.Configuration.WebContext#6](~/add/codesnippet/csharp/p-system.web.configurati_335_1.cs)]\n [!code-vb[System.Web.Configuration.WebContext#6](~/add/codesnippet/visualbasic/p-system.web.configurati_335_1.vb)]"
  syntax:
    content: public string Path { get; }
    return:
      type: System.String
      description: "Percorso virtuale corrente dell&quot;applicazione Web."
  overload: System.Web.Configuration.WebContext.Path*
  exceptions: []
  platform:
  - net462
- uid: System.Web.Configuration.WebContext.Site
  id: Site
  parent: System.Web.Configuration.WebContext
  langs:
  - csharp
  name: Site
  nameWithType: WebContext.Site
  fullName: System.Web.Configuration.WebContext.Site
  type: Property
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  summary: "Ottiene il nome dell&quot;applicazione Web corrente."
  remarks: ''
  example:
  - "The following example shows how to use the Site property. This code example is part of a larger example provided for the <xref:System.Web.Configuration.WebContext> class.  \n  \n [!code-cs[System.Web.Configuration.WebContext#7](~/add/codesnippet/csharp/p-system.web.configurati_287_1.cs)]\n [!code-vb[System.Web.Configuration.WebContext#7](~/add/codesnippet/visualbasic/p-system.web.configurati_287_1.vb)]"
  syntax:
    content: public string Site { get; }
    return:
      type: System.String
      description: "Il nome dell&quot;applicazione Web corrente."
  overload: System.Web.Configuration.WebContext.Site*
  exceptions: []
  platform:
  - net462
- uid: System.Web.Configuration.WebContext.ToString
  id: ToString
  parent: System.Web.Configuration.WebContext
  langs:
  - csharp
  name: ToString()
  nameWithType: WebContext.ToString()
  fullName: System.Web.Configuration.WebContext.ToString()
  type: Method
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  summary: "Restituisce una stringa che rappresenta il percorso di configurazione dell&quot;applicazione."
  syntax:
    content: public override string ToString ();
    parameters: []
    return:
      type: System.String
      description: "Percorso di configurazione dell&quot;applicazione."
  overload: System.Web.Configuration.WebContext.ToString*
  exceptions: []
  platform:
  - net462
references:
- uid: System.Object
  isExternal: false
  name: System.Object
- uid: System.Web.Configuration.WebContext.#ctor(System.Web.Configuration.WebApplicationLevel,System.String,System.String,System.String,System.String,System.String)
  parent: System.Web.Configuration.WebContext
  isExternal: false
  name: WebContext(WebApplicationLevel,String,String,String,String,String)
  nameWithType: WebContext.WebContext(WebApplicationLevel,String,String,String,String,String)
  fullName: System.Web.Configuration.WebContext.WebContext(WebApplicationLevel,String,String,String,String,String)
- uid: System.Web.Configuration.WebApplicationLevel
  parent: System.Web.Configuration
  isExternal: false
  name: WebApplicationLevel
  nameWithType: WebApplicationLevel
  fullName: System.Web.Configuration.WebApplicationLevel
- uid: System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: System.Web.Configuration.WebContext.ApplicationLevel
  parent: System.Web.Configuration.WebContext
  isExternal: false
  name: ApplicationLevel
  nameWithType: WebContext.ApplicationLevel
  fullName: System.Web.Configuration.WebContext.ApplicationLevel
- uid: System.Web.Configuration.WebContext.ApplicationPath
  parent: System.Web.Configuration.WebContext
  isExternal: false
  name: ApplicationPath
  nameWithType: WebContext.ApplicationPath
  fullName: System.Web.Configuration.WebContext.ApplicationPath
- uid: System.Web.Configuration.WebContext.LocationSubPath
  parent: System.Web.Configuration.WebContext
  isExternal: false
  name: LocationSubPath
  nameWithType: WebContext.LocationSubPath
  fullName: System.Web.Configuration.WebContext.LocationSubPath
- uid: System.Web.Configuration.WebContext.Path
  parent: System.Web.Configuration.WebContext
  isExternal: false
  name: Path
  nameWithType: WebContext.Path
  fullName: System.Web.Configuration.WebContext.Path
- uid: System.Web.Configuration.WebContext.Site
  parent: System.Web.Configuration.WebContext
  isExternal: false
  name: Site
  nameWithType: WebContext.Site
  fullName: System.Web.Configuration.WebContext.Site
- uid: System.Web.Configuration.WebContext.ToString
  parent: System.Web.Configuration.WebContext
  isExternal: false
  name: ToString()
  nameWithType: WebContext.ToString()
  fullName: System.Web.Configuration.WebContext.ToString()
- uid: System.Web.Configuration.WebContext.#ctor*
  parent: System.Web.Configuration.WebContext
  isExternal: false
  name: WebContext
  nameWithType: WebContext.WebContext
- uid: System.Web.Configuration.WebContext.ApplicationLevel*
  parent: System.Web.Configuration.WebContext
  isExternal: false
  name: ApplicationLevel
  nameWithType: WebContext.ApplicationLevel
- uid: System.Web.Configuration.WebContext.ApplicationPath*
  parent: System.Web.Configuration.WebContext
  isExternal: false
  name: ApplicationPath
  nameWithType: WebContext.ApplicationPath
- uid: System.Web.Configuration.WebContext.LocationSubPath*
  parent: System.Web.Configuration.WebContext
  isExternal: false
  name: LocationSubPath
  nameWithType: WebContext.LocationSubPath
- uid: System.Web.Configuration.WebContext.Path*
  parent: System.Web.Configuration.WebContext
  isExternal: false
  name: Path
  nameWithType: WebContext.Path
- uid: System.Web.Configuration.WebContext.Site*
  parent: System.Web.Configuration.WebContext
  isExternal: false
  name: Site
  nameWithType: WebContext.Site
- uid: System.Web.Configuration.WebContext.ToString*
  parent: System.Web.Configuration.WebContext
  isExternal: false
  name: ToString
  nameWithType: WebContext.ToString
