### YamlMime:ManagedReference
items:
- uid: System.Configuration.ApplicationSettingsGroup
  id: ApplicationSettingsGroup
  children:
  - System.Configuration.ApplicationSettingsGroup.#ctor
  langs:
  - csharp
  name: ApplicationSettingsGroup
  nameWithType: ApplicationSettingsGroup
  fullName: System.Configuration.ApplicationSettingsGroup
  type: Class
  summary: "Rappresenta un raggruppamento di sezioni di impostazioni applicazione correlata all&quot;interno di un file di configurazione. Questa classe non pu√≤ essere ereditata."
  syntax:
    content: 'public sealed class ApplicationSettingsGroup : System.Configuration.ConfigurationSectionGroup'
  inheritance:
  - System.Object
  - System.Configuration.ConfigurationSectionGroup
  implements: []
  inheritedMembers:
  - System.Configuration.ConfigurationSectionGroup.ForceDeclaration
  - System.Configuration.ConfigurationSectionGroup.ForceDeclaration(System.Boolean)
  - System.Configuration.ConfigurationSectionGroup.IsDeclarationRequired
  - System.Configuration.ConfigurationSectionGroup.IsDeclared
  - System.Configuration.ConfigurationSectionGroup.Name
  - System.Configuration.ConfigurationSectionGroup.SectionGroupName
  - System.Configuration.ConfigurationSectionGroup.SectionGroups
  - System.Configuration.ConfigurationSectionGroup.Sections
  - System.Configuration.ConfigurationSectionGroup.ShouldSerializeSectionGroupInTargetVersion(System.Runtime.Versioning.FrameworkName)
  - System.Configuration.ConfigurationSectionGroup.Type
  platform:
  - net462
- uid: System.Configuration.ApplicationSettingsGroup.#ctor
  id: '#ctor'
  parent: System.Configuration.ApplicationSettingsGroup
  langs:
  - csharp
  name: ApplicationSettingsGroup()
  nameWithType: ApplicationSettingsGroup.ApplicationSettingsGroup()
  fullName: System.Configuration.ApplicationSettingsGroup.ApplicationSettingsGroup()
  type: Constructor
  assemblies:
  - System
  namespace: System.Configuration
  summary: "Inizializza una nuova istanza di <xref href=&quot;System.Configuration.ApplicationSettingsGroup&quot;> </xref> classe."
  syntax:
    content: public ApplicationSettingsGroup ();
    parameters: []
  overload: System.Configuration.ApplicationSettingsGroup.#ctor*
  exceptions: []
  platform:
  - net462
references:
- uid: System.Configuration.ConfigurationSectionGroup
  isExternal: false
  name: System.Configuration.ConfigurationSectionGroup
- uid: System.Configuration.ApplicationSettingsGroup.#ctor
  parent: System.Configuration.ApplicationSettingsGroup
  isExternal: false
  name: ApplicationSettingsGroup()
  nameWithType: ApplicationSettingsGroup.ApplicationSettingsGroup()
  fullName: System.Configuration.ApplicationSettingsGroup.ApplicationSettingsGroup()
- uid: System.Configuration.ApplicationSettingsGroup.#ctor*
  parent: System.Configuration.ApplicationSettingsGroup
  isExternal: false
  name: ApplicationSettingsGroup
  nameWithType: ApplicationSettingsGroup.ApplicationSettingsGroup
